services:
  - type: web
    name: keycloak-server
    runtime: docker

    plan: starter

    autoDeploy: true

    healthCheckPath: /

    envVars:

      - key: KC_DB
        value: postgres

      - key: KC_PROXY_HEADERS
        value: xforwarded

      - key: KC_HTTP_ENABLED
        value: "true"

      - key: KC_HOSTNAME_STRICT
        value: "false"